version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - pip install aws-sam-cli
  build:
    commands:
      - cd backend/spa-sam-app
      - sam build
  post_build:
    commands:
      - sam deploy --stack-name spa-sam-app --resolve-s3 --capabilities CAPABILITY_IAM --no-confirm-changeset