AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 3
    Tracing: Active
    LoggingConfig:
      LogFormat: JSON
  Api:
    TracingEnabled: true

Resources:
  SpaApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowMethods: "'POST,GET,OPTIONS'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key'"
        AllowOrigin: "'*'"

  PutItemFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: put_item/
      Handler: app.lambda_handler
      Runtime: python3.11
      AutoPublishAlias: prod
      DeploymentPreference:
        Type: AllAtOnce
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ItemsTable
      Environment:
        Variables:
          TABLE_NAME: !Ref ItemsTable
      Events:
        PutItemEvent:
          Type: Api 
          Properties:
            Path: /items
            Method: post
            RestApiId: !Ref SpaApi

  GetItemsFunction:     
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: get_items/    
      Handler: app.lambda_handler
      Runtime: python3.11
      AutoPublishAlias: prod
      DeploymentPreference:
        Type: AllAtOnce
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ItemsTable
      Environment:
        Variables:
          TABLE_NAME: !Ref ItemsTable
      Events:
        GetItemsEvent:
          Type: Api
          Properties:
            Path: /items
            Method: get
            RestApiId: !Ref SpaApi

  ItemsTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: ItemsTable
      PrimaryKey:
        Name: id
        Type: String

Outputs:
  ApiEndpoint:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${SpaApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"