AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  ItemsTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: ItemsTable
      PrimaryKey:
        Name: id
        Type: String

  PutItemFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: put_item/
      Handler: app.lambda_handler
      Runtime: python3.11
